wandb_version: 1

epochs:
  desc: null
  value: 9
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 1.1999999999999999e-05
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1744264094.0
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
